{
 "title": "Netflow",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Syslog",
   "type": "table",
   "description": "Syslog table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT * FROM \"siem\".\"syslog\" ORDER BY time DESC LIMIT 1000"
    }
   ]
  },
  {
   "title": "Security Events",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT received, device, type, lvl, action, msg FROM \"siem\".\"events\" ORDER BY received ASC LIMIT 10000"
    }
   ]
  },
  {
   "title": "Total Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeInterval(received) as \"time\", in_bytes FROM \"siem\".\"netflow\" WHERE ( time >= $__fromTime AND time <= $__toTime ) GROUP BY in_bytes, time ORDER BY time DESC LIMIT 10000"
    }
   ]
  },
  {
   "title": "Traffic Distribution by DST ASN",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT dst_asn, dst_asn_org, in_bytes FROM siem.netflow ORDER BY in_bytes DESC"
    }
   ]
  },
  {
   "title": "Traffic Distribution by SRC ASN",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT src_asn, src_asn_org, in_bytes FROM siem.netflow ORDER BY in_bytes DESC"
    }
   ]
  },
  {
   "title": "TCP destination port by IP  ",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "rawSql": "SELECT received AS time, proto, dst_port, dst4_addr FROM \"siem\".\"netflow\" where proto='tcp' ORDER BY time"
    }
   ]
  },
  {
   "title": "TCP source port by IP",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "rawSql": "SELECT proto, src_port, src4_addr, in_bytes FROM \"siem\".\"netflow\" where proto='tcp'"
    }
   ]
  },
  {
   "title": "UDP DST",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "rawSql": "select dst_port, dst4_addr, sum(in_bytes) FROM siem.netflow WHERE proto='udp' AND dst_port >= 0 GROUP BY dst_port, dst4_addr"
    }
   ]
  },
  {
   "title": "UDP traffic by source IP",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "targets": [
    {
     "rawSql": "select received as time, src_port, src4_addr, sum(in_bytes) FROM siem.netflow WHERE proto='udp' AND src_port >= 0 GROUP BY time, src_port, src4_addr ORDER BY time DESC"
    }
   ]
  },
  {
   "title": "Protocol Distribution",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT sum(in_bytes), proto FROM \"siem\".\"netflow\" GROUP BY proto LIMIT 10000"
    }
   ]
  }
 ]
}